### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by duynht** [trungdt21/svm-from-scratch#1]
# Task 1: Inference
- [ ] Keep training data during inference (different from regression/classification: keep weight)
- [ ] Define public API for SVM: store param; given param how to inference to get the prediction
- [ ] Later on, keep only the support vectors.
