### ISSUE TITLE
Kernelized SVM

### ISSUE THREAD

**Issue by duynht** [trungdt21/svm-from-scratch#2]
# Task 2: Kernelize SVM
- [x] An interface for SVM with different kernel functions.
- [x] Supported kernels follow Mercer's theorem: positive semi-definite matrix (e.g., Radial Basis Function)
- [x] Create testing program for svm kernels

**Comment by v-namtd12** [comment]
Ok, let me do this task!
My approach:
1. Create a class define kernel SVM (4 types for now)
- Linear, polynomial, RBF, sigmoid
2. Create a program to test the results and speed of specific kernels (compare numpy vs the rest)
3. Pull to our project and integrate with other tasks
