### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by duynht** [trungdt21/svm-from-scratch#3]
# Task 3: Training
- [ ] Use off-the-shelf optimizer: [cvxopt](https://cvxopt.org/examples/tutorial/qp.html)
- [ ] Calculate Q, p, G, h, A, b using training data.
- [ ] Understand those params.
- [ ] Unit test: Test if code is working or not.

**Reference:** Bishop's Chapter 7 (Sparse Kernel Machines ~ quadratic programming problem).

**Comment by v-trungdt21** [comment]
implemented
